language: swift

branches:
  except:
    - gh-pages

install:
  - gem install cocoapods --pre -N
  - gem install xcpretty -N

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="CrashReporter"

matrix:
  include:
    - osx_image: xcode10.1
      env: SCHEME="macOS"    SDK="macosx10.14"        DESTINATION="arch=x86_64"                    SWIFT_VERSION="4.2" ACTION="test"
    - osx_image: xcode10.2
      env: SCHEME="macOS"    SDK="macosx10.14"        DESTINATION="arch=x86_64"                    SWIFT_VERSION="5.0" ACTION="test"

script:
  - set -o pipefail
  - pod --version
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    "$ACTION"
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    SWIFT_VERSION=$SWIFT_VERSION
  - pod lib lint --quick

after_success:
  - bash <(curl -s https://codecov.io/bash)
